# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Tag',
            new_name='Tab',
        ),
    ]
